refactor: refactored mainwindow
uyraq2001/alterator-browser pull request #27
Opened 2023-09-01 14:40 UTC by uyraq2001

2023-09-01 14:47 UTC, mchernigin requested changes

2023-09-01 14:47 UTC, mchernigin commented on src/app/mainwindow.cpp
> +        , settings(std::make_unique<MainWindowSettings>(window, ui)){}
Not formatted correctly for some reason.

2023-09-01 14:47 UTC, mchernigin commented on src/app/mainwindow.cpp
> +        model.release();
Smart pointers deallocate memory in the destructor. If you call release, you are taking "ownership" responsibility to deallocate memory yourself. But in this case you don't.

This 2 lines should not be here.

2023-09-01 14:47 UTC, mchernigin commented on src/app/mainwindow.cpp
>      : QMainWindow(parent)
Do we actually need to initialize QMainWindow if we MainWindow is derived from QMainWinow?

2023-09-01 14:54 UTC, mchernigin commented on src/app/mainwindow.cpp
> +        model.release();
If you don't actually "own" underlying data, you should not use `unique_ptr` here.

2023-09-04 10:07 UTC, AlexSP0 requested changes

2023-09-04 10:07 UTC, AlexSP0 commented on src/app/controller.cpp
> +    , d(new ControllerPrivate)
How long does ControllerPrivate live?

2023-09-06 07:43 UTC, mchernigin approved these changes

2023-09-07 05:41 UTC, AlexSP0 approved these changes

2023-09-07 09:30 UTC, merged