refactor: removed repeating code in model (re)building
uyraq2001/alterator-browser pull request #31
Opened 2023-09-07 09:33 UTC by uyraq2001

2023-09-12 09:13 UTC, AlexSP0 requested changes

2023-09-12 09:13 UTC, AlexSP0 commented on src/app/pushbutton.cpp
>      this->setMenu(menu.release());
QPushButton does not own QMenu, neither does the unique pointer. Possible memory leak?

2023-09-13 12:25 UTC, AlexSP0 approved these changes

2023-09-18 06:02 UTC, mchernigin requested changes

2023-09-18 06:02 UTC, mchernigin commented on src/app/model/application.h
> +    QString m_implementedInterface;
Add default initialization so there is no need for constructor

2023-09-18 06:02 UTC, mchernigin commented on src/app/model/object.cpp
> +    //    }
Should be removed

2023-09-18 06:02 UTC, mchernigin commented on src/app/model/object.h
> +    //    std::unique_ptr<ObjectCategory> m_categoryObject{nullptr};
Should be removed

2023-09-18 07:12 UTC, mchernigin requested changes

2023-09-18 07:12 UTC, mchernigin commented on src/app/model/abstractentity.h
> +    ~AbstractEntity();
Is it needed?

2023-09-18 07:12 UTC, mchernigin commented on src/app/model/objectsmodelbuilder.h
> +    QString m_getDesktopFileMethodName;
Should be default initialized

2023-09-27 12:58 UTC, mchernigin commented on src/app/model/object.h
> +    bool m_isLegacy{};
nit: could be more verbose with `= false`

2023-09-27 13:32 UTC, mchernigin requested changes

2023-09-27 13:32 UTC, mchernigin commented on src/app/pushbutton.cpp
> +    auto t     = newItem->getObject();
Why `t` exists? Can we just use `newItem->getObject()` in next line? In this case there is no need for `std::move`.

2023-09-27 13:32 UTC, mchernigin commented on src/app/pushbutton.cpp
> +    //    auto b            = t;
Remove this comment

2023-09-27 13:32 UTC, mchernigin commented on src/app/pushbutton.h
> +    PushButton &operator=(PushButton &&) = delete;
Deleted member functions should be public. Then compiler can provide much better error message once you try to use it.

2023-09-27 13:32 UTC, mchernigin commented on src/app/pushbutton.h
> +    ~PushButton() = default;
Also why remove override?

2023-09-27 13:32 UTC, mchernigin commented on src/app/model/objectitem.h
> +    ~ObjectItem() = default;
Why remove override? I think it should be added to all functions that override base class behaviour.

> The override keyword serves two purposes: It shows the reader of the code that "this is a virtual method, that is overriding a virtual method of the base class." The compiler also knows that it's an override, so it can "check" that you are not altering/adding new methods that you think are overrides.
>
> https://stackoverflow.com/questions/18198314/what-is-the-override-keyword-in-c-used-for

2023-09-27 13:32 UTC, mchernigin commented on src/app/model/objectitem.h
> +    ~ObjectItem() = default;
Why remove deletion of copy(move) assignment operators and constructors?

2023-09-27 13:32 UTC, mchernigin commented on src/app/model/objectsmodelbuilder.cpp
> +        ObjectItem *currentCategoryItem    = dynamic_cast<ObjectItem *>(currentStandardItem);
Why repeat type on the left side of assignment when it is verbose on right? I think it is better to use auto.

2023-09-27 13:32 UTC, mchernigin commented on src/app/model/objectsmodelbuilder.cpp
> +        ObjectItem *currentModuleItem      = dynamic_cast<ObjectItem *>(currentStandardItem);
Also why repeat type on the left side of assignment when it is verbose on right?

2023-09-27 13:32 UTC, mchernigin commented on src/app/model/objectsmodelbuilder.cpp
> +            for (std::size_t j = 0; j < std::get<ab::model::Object>(currentModuleItem->getObject()).m_interfaces.size();
Nit: maybe it is better to extract long `size()` call to constant?

2023-09-27 13:32 UTC, mchernigin commented on src/app/model/objectsmodelbuilder.cpp
> +        qWarning() << "Can't reply with category name for the category: " << categoryName;
You don't need to add space on the end of string literal. Logger implementation automatically adds space between operands. For example, `qWarning() << "abc" << 123;` will produce `"...: abc 123"`

2023-10-03 14:27 UTC, mchernigin requested changes

2023-10-03 14:27 UTC, mchernigin commented on src/app/model/objectsmodelbuilder.cpp
> +        qWarning() << "Can not connect to " + CATEGORY_INTERFACE_NAME_FOR_ACOBJECT + " interface";
Maybe it is a good idea to return early here? Should you call `iface->call` if interface is not valid?

2023-10-03 14:27 UTC, mchernigin commented on src/app/model/objectitem.cpp
> +    return m_object.get(); //is it the best way?
Format comments like this:
`// NOTE(uyraq2001): I'm not sure if it's the best way?`

2023-10-03 14:27 UTC, mchernigin commented on src/app/model/objectitem.cpp
> +std::variant<Object, Category>* ObjectItem::getObject()
Not formatted correctly: `*` should be on the right

2023-10-03 14:27 UTC, mchernigin commented on src/app/model/object.h
> +    bool m_isLegacy{};
Do you think it is better to leave as is or forgot to change? I think it's better to add comment if you are resolving conversation without making a change

2023-10-03 14:27 UTC, mchernigin commented on src/app/model/objectbuilder.h
> +    ObjectBuilder &operator=(ObjectBuilder &&) = delete;
You can delete this 4 lines: there is no need to define copy and move assignment and constructor, if you don't define destructor.

2023-10-03 14:27 UTC, mchernigin commented on src/app/model/objectitem.h
> +    ~ObjectItem()                        = default;
Add `override`.

2023-10-03 14:27 UTC, mchernigin commented on src/app/model/objectsmodelbuilder.cpp
> +    , m_getDesktopFileMethodName(getDesktopFileMethod)
Why delete `std::move`? Now there is one more string construction for each argument.

2023-10-04 09:58 UTC, mchernigin approved these changes

2023-10-10 10:20 UTC, AlexSP0 requested changes

2023-10-10 10:20 UTC, AlexSP0 commented on src/app/model/objectsmodelbuilder.cpp
> +        auto interfaces = std::get<ab::model::Object>(*currentModuleItem->getObject()).m_interfaces;
It is expected that there will be an object of type Category. However, if there is an object of a different type here, an unhandled exception will be thrown and the program will crash. I suggest handling this exception.

2023-10-10 10:20 UTC, AlexSP0 commented on src/app/pushbutton.cpp
> +    model::Object obj = std::get<ab::model::Object>(*newItem->getObject());
It is expected that there will be an object of type Object. However, if there is an object of a different type here, an unhandled exception will be thrown and the program will crash. I suggest handling this exception.

2023-10-13 08:12 UTC, merged